# Generated by Django 5.2 on 2025-04-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='instructions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
